[package]
name = "smartcore-examples"
version = "0.1.0"
authors = ["SmartCore Dvelopers"]
edition = "2018"

[dependencies]
smartcore = { path = "../smartcore", features=["nalgebra-bindings", "ndarray-bindings", "datasets"]}
structopt = "0.3.17"
ndarray = "0.13"
nalgebra = "0.22.0"